<?php

namespace Efrei\Readyo\MusicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MusicPlayedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicPlayedRepository extends EntityRepository
{
}
