api_v1_user_profile:
    type:     rest
    path:     /users/me
    defaults: { _controller: EfreiReadyoUserBundle:UserApi1:profile }
    requirements:
        _method:  GET


api_v1_user_edit:
    type:     rest
    path:     /users/me/edit
    defaults: { _controller: EfreiReadyoUserBundle:UserApi1:editProfile }
    requirements:
        _method:  POST