<?php

namespace Efrei\Readyo\WebradioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PodcastCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodcastCommentRepository extends EntityRepository
{
}
