<?php

namespace Efrei\Readyo\WebradioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PodcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodcastRepository extends EntityRepository
{
	public function findByShow($showId, $type, $limit, $offset) {
		
		$qb = $this->createQueryBuilder('podcast')
		    ->leftJoin('podcast.schedule', 'schedule');

		$qb
			->where('schedule.show = :showId')
			->setParameter('showId', $showId)
			->andWhere('schedule.isPublish = 1')
		;

		if($type)
			$qb
				->andWhere('podcast.type = :type')
				->setParameter('type', $type)
			;

		$qb->orderBy('podcast.uploadAt', 'ASC')
			
			->setFirstResult( $offset )
   			->setMaxResults( $limit );
		;


		return $qb
			->getQuery()
			->getResult()
		;
	}
}
