<?php

namespace Efrei\Readyo\WebradioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Show2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
}
