parameters:
#    efrei_readyo_live.example.class: Efrei\Readyo\LiveBundle\Example

services:
#    efrei_readyo_live.example:
#        class: %efrei_readyo_live.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
