imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Efrei\Readyo\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        #form:
        #    type: fos_user_rest_registration
        confirmation:
            from_email:
                address:        noreply@readyo.fr
                sender_name:    Ready'O Efrei
            enabled: true
            template:   EfreiReadyoUserBundle:Registration:email.html.twig

lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      'awiz@readyo'                           # ssh key pass phrase
    token_ttl:        86400                                   # token ttl - defaults to 86400


fos_rest:
    disable_csrf_role: ROLE_USER
    param_fetcher_listener: true
    body_listener: true
    routing_loader:
        default_format: json
    view:
        jsonp_handler: ~
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener: false

sensio_framework_extra:
    view:
        annotations: false

nelmio_api_doc: ~

jms_serializer:
    metadata:
        auto_detection: true
        directories:
          FOSUserBundle:
            namespace_prefix: "FOS\\UserBundle"
            path: "@EfreiReadyoUserBundle/Resources/config/serializer/fos"

knp_time: ~

varspool_websocket:
    servers:
        default: # Server name
            listen: "ws://%palladium_host%:%palladium_port%" # default: ws://localhost:8000

            # Applications this server will allow
            applications:
                - palladium

            # Origin control
            check_origin: true
            allow_origin: # default: just localhost (not useful!)
                - "localhost"
                - "127.0.0.1"
                - "192.168.155.2"
                - "192.168.155.14"
               # - "development.localdomain"

            # Other defaults
            max_clients:             200
            max_connections_per_ip:  10
            max_requests_per_minute: 0