<?php

namespace Efrei\Readyo\PalladiumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalladiumMessageRepository extends EntityRepository
{
}
