
############
### SHOW ###
############

api_v1_webradio_show_list:
    type:     rest
    path:     /shows
    defaults: { _controller: EfreiReadyoWebradioBundle:ShowApi1:list }
    requirements:
        _method:  GET

api_v1_webradio_show_details:
    type:     rest
    path:     /shows/{$showId}
    defaults: { _controller: EfreiReadyoWebradioBundle:ShowApi1:show }
    requirements:
        _method:  GET

api_v1_webradio_show_details_schedules:
    type:     rest
    path:     /shows/{$showId}/schedules
    defaults: { _controller: EfreiReadyoWebradioBundle:ShowApi1:schedules }
    requirements:
        _method:  GET

api_v1_webradio_show_details_podcasts:
    type:     rest
    path:     /shows/{$showId}/podcasts
    defaults: { _controller: EfreiReadyoWebradioBundle:ShowApi1:podcasts }
    requirements:
        _method:  GET




################
### SCHEDULE ###
################

api_v1_webradio_schedule_list:
    type:     rest
    path:     /schedules
    defaults: { _controller: EfreiReadyoWebradioBundle:ScheduleApi1:list }
    requirements:
        _method:  GET

api_v1_webradio_schedule_details:
    type:     rest
    path:     /schedules/{$scheduleId}
    defaults: { _controller: EfreiReadyoWebradioBundle:ScheduleApi1:show }
    requirements:
        _method:  GET


api_v1_webradio_schedule_details_podcasts:
    type:     rest
    path:     /schedule/{$scheduleId}/podcasts
    defaults: { _controller: EfreiReadyoWebradioBundle:ScheduleApi1:podcasts }
    requirements:
        _method:  GET


###############
### PODCAST ###
###############

api_v1_webradio_podcast_list:
    type:     rest
    path:     /podcasts
    defaults: { _controller: EfreiReadyoWebradioBundle:PodcastApi1:list }
    requirements:
        _method:  GET


api_v1_webradio_podcast_details:
    type:     rest
    path:     /podcasts/{$podcastId}
    defaults: { _controller: EfreiReadyoWebradioBundle:PodcastApi1:show }
    requirements:
        _method:  GET

api_v1_webradio_podcast_details_comments_list:
    type:     rest
    path:     /podcasts/{$podcastId}/comments
    defaults: { _controller: EfreiReadyoWebradioBundle:PodcastApi1:listComments }
    requirements:
        _method:  GET

api_v1_webradio_podcast_details_comments_add:
    type:     rest
    path:     /podcasts/{$podcastId}/comments
    defaults: { _controller: EfreiReadyoWebradioBundle:PodcastApi1:postComments }
    requirements:
        _method:  POST