<?php

namespace Efrei\Readyo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends EntityRepository
{

	public function revoke($user, $ip, $plateform, $expiredAt) {

		$tokens = $this->createQueryBuilder('e')
			->where('e.user = :user')
			->setParameter('user', $user->getId())

			->andWhere('e.ip = :ip')
			->setParameter('ip', $ip)

			->andWhere('e.isRevoked = :isRevoked')
			->setParameter('isRevoked', false)

			->andWhere('e.plateform = :plateform')
			->setParameter('plateform', $plateform)

			->andWhere('e.expiredAt <= :expiredAt')
			->setParameter('expiredAt', $expiredAt)
			->getQuery()
			->getResult();
		
		foreach($tokens as $token) {

			$token->setIsRevoked(true);
			$this->_em->persist($token);	
		}

		$this->_em->flush();
	}
}
