<?php

namespace Efrei\Readyo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPictureRepository extends EntityRepository
{
}
